### ISSUE TITLE
Some devices must not have allowedMode Property

### ISSUE THREAD

**Issue by thecloudtaylor** [thecloudtaylor/hubitat-honeywell#7]
https://github.com/thecloudtaylor/hubitat-honeywell/blob/7278c243c2098bf92f2ec44ec172018afec56e20/honeywellhomeapp.groovy#L541

Log error on installation, but installed okay and created child device.
app:553 2020-11-29 10:27:05.817 am errorjava.lang.NullPointerException: Cannot get property 'allowedModes' on null object on line 541 (appButtonHandler)

**Comment by thecloudtaylor** [comment]
I think the _right_ fix is to create two different drivers or at least delineate them but I worry about long term maintainability. Hopefully this "fix" works for now.

**Comment by WiredContact** [comment]
Hi Taylor following on from the chat in https://community.hubitat.com/t/hubitatcommunity-honeywellthermo-tcc/57896/17

As an extensive user of Evohome in the UK I very interested in seeing how this evolves. Resideio are clearly interested and responsive to Hubitat engagement - I've been speaking with Anda at consumersupportuk@resideo.com  Subject: 08252974 - Evohome connection with HttPS://Hubitat.com [ ref:_00D6A2HOku._5002GryFA7:ref ]

I have three base units each controlling upto 9 radiators and propose to extend the usage to another 20 radiators.

Resideo have a massive opportunity Worldwide if they can help you get this over the line. 
Kind Regards
Paul
